# Generated by Django 5.2.4 on 2025-07-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('monthly', 'Monthly')], default='once', max_length=150),
        ),
    ]
