# Generated by Django 5.2.4 on 2025-08-01 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donation_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='background',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.TextField(blank=True, help_text='List of completed actions, as bullet points', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='percentage_funded',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
