# Generated by Django 5.1.6 on 2025-08-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], default='USD', max_length=3),
        ),
    ]
