# Generated by Django 5.2.4 on 2025-08-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_plan_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donation',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'ONCE'), ('MONTHLY', 'MONTHLY')], default='ONCE', max_length=150),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=20),
        ),
    ]
