# Generated by Django 5.2.4 on 2025-08-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_donation_payment_plan_code_donation_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_client',
            field=models.CharField(blank=True, default='PAYSTACK', max_length=255, null=True),
        ),
    ]
