# Generated by Django 5.2.4 on 2025-08-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_donation_payment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphoto',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
