# Generated by Django 5.2.4 on 2025-08-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_projectphoto_date_projectphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='receiving_donation',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
