# Generated by Django 5.2.4 on 2025-08-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_receiving_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphoto',
            old_name='date',
            new_name='deliver_date',
        ),
    ]
