# Generated by Django 5.2.4 on 2025-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_date_projectphoto_deliver_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donation_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
