# Generated by Django 5.2.4 on 2025-08-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_donation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='agreement_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
