# Generated by Django 5.2.4 on 2025-08-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_donation_agreement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiary_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_phrase',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
