# Generated by Django 5.2.4 on 2025-08-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('lab-tech', 'Lab Technician'), ('computer-tech', 'Computer Technician'), ('medical-tech', 'Medical Technician'), ('other', 'Other')], max_length=50)),
                ('availability', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time')], max_length=50)),
                ('hours', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.CharField(blank=True, max_length=50, null=True)),
                ('cv', models.FileField(upload_to='volunteer_cvs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20),
        ),
    ]
