# Generated by Django 5.2.4 on 2025-08-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_project_beneficiary_count_project_impact_count_and_more'),
        ('api', '0014_volunteer_alter_project_status'),
    ]

    operations = [
    ]
