# Generated by Django 5.2.4 on 2025-08-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20250814_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('community', 'Community Development'), ('healthcare', 'Healthcare')], max_length=20, null=True),
        ),
    ]
