# Generated by Django 5.2.4 on 2025-08-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='beneficiary_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
