# Generated by Django 5.2.4 on 2025-08-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_project_beneficiary_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='impact_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
