# Generated by Django 5.2.4 on 2025-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_project_impact_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='milestones',
            field=models.JSONField(blank=True, default=str, help_text='List of completed actions, as bullet points', null=True),
        ),
    ]
