# Generated by Django 5.2.4 on 2025-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_project_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='goals',
            field=models.JSONField(blank=True, default=list, help_text='List of completed actions, as bullet points', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='List of completed actions, as bullet points', null=True),
        ),
    ]
