# Generated by Django 5.2.4 on 2025-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_donation_converted_amount_project_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('USD', models.DecimalField(decimal_places=2, default=1600, max_digits=10)),
                ('NGN', models.DecimalField(decimal_places=6, default=0.00065, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
