# Generated by Django 5.2.4 on 2025-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_newslettersubscription_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('lab-tech', 'Lab Technician'), ('computer-tech', 'Computer Technician'), ('medical-tech', 'Medical Technician'), ('other', 'Other')], max_length=50)),
                ('availability', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time')], max_length=50)),
                ('hours', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.CharField(blank=True, max_length=50, null=True)),
                ('cv', models.FileField(upload_to='volunteer_cvs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
