# Generated by Django 5.2.4 on 2025-08-21 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_newslettersubscription_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-effective_date'], 'verbose_name': 'Exchange Rate', 'verbose_name_plural': 'Exchange Rates'},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='converted_amount',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='NGN',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='USD',
        ),
        migrations.AddField(
            model_name='donation',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used for conversion', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='parent_donation',
            field=models.ForeignKey(blank=True, help_text='Original donation for recurring payments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='api.donation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='project_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to project currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='ngn_to_usd_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How many USD equals 1 NGN (e.g., 0.000625)', max_digits=10),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='usd_to_ngn_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How many NGN equals 1 USD (e.g., 1600.0000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='agreement_id',
            field=models.CharField(blank=True, help_text='For recurring payment agreements', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in the currency the donor paid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], help_text='Currency the donor paid in', max_length=3),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_client',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('PAYPAL', 'PayPal')], default='PAYSTACK', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='reference',
            field=models.CharField(db_index=True, help_text='Payment gateway reference', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('community', 'Community Development'), ('healthcare', 'Healthcare'), ('environment', 'Environment'), ('emergency', 'Emergency Relief')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='receiving_donation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_email', 'status'], name='api_donatio_donor_e_0290b7_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['project', 'status'], name='api_donatio_project_a8a0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['reference'], name='api_donatio_referen_83beec_idx'),
        ),
    ]
