# Generated by Django 5.2.4 on 2025-08-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_donation_options_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='previous_amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
