# Generated by Django 5.2.4 on 2025-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_project_previous_amount_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('NGN', 'NGN')], help_text='Currency the project is in', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
