# Generated by Django 5.2.4 on 2025-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_donation_project_currency_donation_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='previous_amount_raised',
        ),
        migrations.AddField(
            model_name='donation',
            name='current_amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='donation',
            name='previous_amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
