# Generated by Django 5.2.4 on 2025-08-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_project_previous_amount_raised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='achievments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
