# Generated by Django 5.2.4 on 2025-08-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_project_achievments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='achievments',
            new_name='achievements',
        ),
    ]
