# Generated by Django 5.2.4 on 2025-08-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_achievments_project_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='achievements',
            new_name='donation_supports',
        ),
    ]
