# Generated by Django 5.2.4 on 2025-08-26 20:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_volunteer_email_volunteer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt_sent',
            field=models.BooleanField(default=False, help_text='True once donation receipt emailed to donor'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cv',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='static/media'), upload_to='volunteer_cvs/'),
        ),
    ]
